spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bdtalk2gether?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
#   url: jdbc:mysql://containers-us-west-32.railway.app:6471/talk2gether?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false&allowPublicKeyRetrieval=true
#   username: root
#   password: OrDXp80oH8kyaDPMs1Iv
#    url: jdbc:mysql://localhost:3306/bdtalk2gethertest?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: "America/Argentina/Buenos_Aires"
  
  mail:
    host: smtp.office365.com
    port: 587
    username: talk2gether.soporte@hotmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
